algolia/algoliasearch-rails

- README.md
Not sure if that's an inside joke or not (I looked it up on Urban Dictionary, regardless :) but this makes it more clear.
> Replaced "noop" with "not run".

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
> Ensure enqueued job respect the without_auto_index constraints

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
> SafeIndex: ensure we're forward the block.

- README.md
I didn't found an example to co configure `attributeForDistinct` through the code so I added that.
> Add example to configure grouping

- README.md
- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
@alexandremeunier had started it, but I think to keep the backward comp we can't just do a `sed` here.
Closes #154 .
> feat(replica): replace slaves by replica while keeping backward comp

- README.md
- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
Adds a `forward_to_replicas` parameter to the main `algoliasearch`block.
> feat(replicas): new `inherit` parameter

- README.md
Updating the 'With Sidekiq' section in /README.md
Belongs to #229
> Update README Sidekiq example

- lib/algoliasearch/utilities.rb
> Use puts instead of say

- lib/algoliasearch-rails.rb
> Add paginationLimitedTo setting.

- algoliasearch-rails.gemspec
Fixes algolia/algoliasearch-client-ruby#200
> Update algoliasearch version

- .travis.yml
- Gemfile
- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
> Add ActiveModel::Serializer support

- README.md
Just fixing a link in the README :)
> README: fix link to Custom objectID section

- README.md
missing "s" to attribute
See title
> Update code snippet in README

- .travis.yml
> chore: adds Rails 6 to CI matrix

- .circleci/config.yml
- Gemfile
- README.md
- lib/algoliasearch/utilities.rb
- spec/integration_spec.rb
Switch from Travis to CircleCI
> chore: adds circleCI

- .circleci/config.yml
- .gitignore
- Gemfile
- algoliasearch-rails.gemspec
- lib/algoliasearch-rails.rb
- lib/algoliasearch/configuration.rb
- lib/algoliasearch/version.rb
- spec/integration_spec.rb
- spec/spec_helper.rb
- spec/utilities_spec.rb
This PR updates the dependency to the `algoliasearch` gem to `algolia` gem. 
This will be a new major considering the breaking changes introduced in `algolia` new gem.
TODO: update Algolia's doc
> release: v2

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
| New feature?      | yes
| Related Issue     | #386
Backport the `:virtual` option.
> Implement virtual replicas

- CHANGELOG.MD
- lib/algoliasearch/version.rb
| Bug fix?          | yes/no
| New feature?      | yes/no    
| Need Doc update   | yes/no
> chore: bumps version to v1.26.0

- lib/algoliasearch-rails.rb
| Related Issue     | 
Wrong indentation when reading the codebase.
Correctly align with the closing `end`
> Fix wrong indent

- README.md
| Related Issue     | Fix #399
> chore: update index initialization docs

- lib/algoliasearch/configuration.rb
| New feature?      | no  
| Related Issue     | fix #428 
Fix method name
Unintended name
> Fix wrong method name
