algolia/algoliasearch-rails

- README.md
I was confused what the index default was until I read the code comments in the **Per-Environment Indexes** section.
> Add default index name to README.

- .gitignore
- Gemfile
- Gemfile.lock
- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
This pull request aims to add Sequel ORM support to this gem, however it is still experimental and at the time of writing the specs aren't passing yet.
Things that are working:
- Re/Indexing of records
- Asynchronous after_save/after_destroy updates
Items I need help with:
/cc @redox
> Sequel ORM support

- README.md
The JS API Client included in the gem is V3, but the notation in the instruction here is for V2.
> Change the JS notation to V3

- lib/algoliasearch-rails.rb
This might have been a new parameter for ranking purposes. See screenshot below.
> allow :allowTyposOnNumericTokens to be configured

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
Changes:
When building algolia_configurations check if each index_settings obj has additional indexes, and if so extract them to the top level of configurations.
To consider:
Is there a use case for deeper levels of nesting than this?  If so a more intelligent solution would probably need to be found.
> Allow nested add_slave declarations within add_index blocks to be used.

- lib/algoliasearch-rails.rb
You can disable indexing temporarily using `ClassName.without_auto_index`, but this didn't quite work if you're using a queue due to a race condition. This commit should fix it.
...not sure how to test this though.
> Fix race condition for without_auto_index

- README.md
An important part to getting things up and running. I had to look elsewhere to find out how to initially index my models.
_There is an outdated Rake task that is suppose to accomplish indexing all your models. If you get that working again, I'd recommend replacing my `descendents` method with calling your Rake task._
> Added Indexing section to the Quick Start in README.

- lib/algoliasearch-rails.rb
This prevents attribute values from being computed when running `algolia_must_reindex?`, i.e. when checking whether the object should be reindexed in the `after_validation` hook.
This should fix #101
> Refactored IndexSettings#get_attributes and added IndexSettings#get_attribute_names

- lib/algoliasearch-rails.rb
Index settings has a typo on the parameter [disableTypoToleranceOnAttributes](https://www.algolia.com/doc/rest-api/search#param-disableTypoToleranceOnAttributes-2)
Renamed parameter from **disableTypoToleranceOn** to **disableTypoToleranceOnAttributes**
> disable_tolerance_typo # fix disableTypoToleranceOnAttributes typo

- lib/algoliasearch-rails.rb
Adds disablePrefixOnAttributes and disableTypoToleranceOnAttributes.
Fixes #193
> Whitelist extra options for Algolia API

- lib/algoliasearch-rails.rb
Not sure why, and if this means we forgot to keep backward comp in `algoliasearch-client-ruby`.
> fix(AlgoliaError): e.status isn't defined, e.code is

- lib/algoliasearch/tasks/algoliasearch.rake
- lib/algoliasearch/utilities.rb
• Updated `AlgoliaSearch::Utilities::get_model_classes` with `respond_to?(:reindex)` checked.
-> Prior to this, it was always return an empty array.
• Update `reindex_all_models` to list models being reindexed and provide console output on the number of records being reindexed.
Here's what the updated output looks like now when you run it: 
Fixes #37.
> Fix algoliasearch:reindex rake task.

- lib/algoliasearch-rails.rb
This is a fix for https://github.com/algolia/algoliasearch-rails/issues/234
This makes the `algolia_without_auto_index_scope` thread safe.  Change is to start using `Thread.current` to set and store the scope instead of a class instance variable.  This makes the scope thread safe.
> Make `algolia_without_auto_index_scope` thread safe

- lib/algoliasearch-rails.rb
While mocking the API, those JSON fields could be missing. Ensure we
manipulate integers and not nil values.
Fix #242
> Fixed NPE in test environments.

- lib/algoliasearch-rails.rb
Simply converts objectID to string before using it as a hash key.
> Fix for broken search

- lib/algoliasearch-rails.rb
Since we're still using the first version of the synonyms in the Rails
integration, let's force the settings to bet get as v1.
> Get Settings & Synonyms

- Gemfile
- Gemfile.lock
- lib/algoliasearch/version.rb
In order to have access to the new Query Rules endpoints.
> Upgrade algoliasearch gem to 1.17.0

- lib/algoliasearch-rails.rb
Requiring RubyGems is not necessary since Ruby 1.8, and requiring/initializing Bundler breaks our app startup since Bundler 1.16. 
Here's a stack trace: 
```
ArgumentError:
Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
``` 
Things work without the deleted require statements.
> Do not require rubygems or bundler

- .travis.yml
- spec/spec_helper.rb
Testing Key Dealer project. This should allow public PRs to run specs with a custom key valid only for this PR.
cc @julienbourdeau
> Use Algolia Key Dealer to allow contributors outside of Algolia to run Travis

- .travis.yml
- Gemfile
- Gemfile.lock
- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
Try to apply the patch offered by the Changelog linked by
@redox in #264.
I believe this way is the proper way of finally solving the issue
I've added an entry to the travis build matrix to test with:
- Rails 5 with Sequel 4
- Rails 5 with Sequel 5
Closes #264
Closes #270
Reverts #287
> fix(sequel): correctly call after_commit for Sequel 5.0

- lib/algoliasearch-rails.rb
The array of options had two times `:disableTypoToleranceOnAttributes`
> Duplicated attributes in array of options

- spec/spec_helper.rb
When a job number is 92.4, we only used the last part (4 in this
example). but if the build job 93 starts at the same time, there
will be a 93.4 job conflicting with 92.4.
> Fix Travis index names

- lib/algoliasearch-rails.rb
| New feature?      | no 
| Related Issue     | Fix #263
This is the same code as PR https://github.com/algolia/algoliasearch-rails/pull/263 (which has been stale for more than a year), but fixed with all tests hopefully passing.
PR https://github.com/algolia/algoliasearch-rails/pull/263 used `ActiveRecord::Version` which doesn't exist: only `ActiveRecord::VERSION` exists. My PR fixes that.
The end goal of both this PR and the original PR is to use non-deprecated fields.
> Don't use deprecated attribute_changed?

- lib/algoliasearch-rails.rb
| Related Issue     | Fix #328 
If ActiveRecord is not loaded, the change introduced in #325 would break. This fix makes sure ActiveRecord is loaded before accessing its contants.
> Ensure ActiveRecord is loaded (fix #328)

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
This add a const for default batch size integer
Specs are failing locally not sure why and does not look related with this PR:
```
1) FowardToReplicas shouldn't have inherited from the primary
Failure/Error: expect(replica_settings['attributesToIndex']).to eq(nil)
expected: nil
got: ["second_value"]
(compared using ==)
```
> Add DEFAULT_BATCH_SIZE const

- .travis.yml
- Gemfile
- lib/algoliasearch-rails.rb
| New feature?      | yes    
```ruby
algoliasearch per_environment: true do
searchableAttributes ['name', 'unordered(email)', 'company']
attributesForFaceting ['company']
keepDiacriticsOnCharacters "char"
end
```
In order to manage your settings as show before, all settings must be declared by the extension. I have updated the list and reorganize it according to the [documentation](https://www.algolia.com/doc/api-reference/api-parameters/query/), hoping this would make it easier to update
> Add support for all recent settings

- spec/spec_helper.rb
| Related Issue     | Fix #323 
The change is a method to delete indexes after the test suite runs & to make `index_names` truely unique to prevent concurreny issues.
1. Add secure random for true unique index names.
1. Add a rails specific prefix for easy identification.
1. Filter created indexes by secure random for deleting.
1. Sort indices so we don't attempt to delete a replica or slave before its primary.
The below example show the safe execution does not delete the `DoNotDelete` index.
spec/integration_spec.rb:962 expects a replica to contain `nil` in `attributesToIndex`
spec/integration_spec.rb:974 adds `second_value` to …
> Add safe index name prefix and after suite index deletion

- Gemfile
Recent update of sqlite3 gem seems to break the build :( 
No idea why
> Install version 1.3 of gem sqlite3

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
| New feature?      | yes    
| Related Issue     | Fix #140   
We recently made some change to handle the new `will_save_change_to_#{attr}?` instead of the deprecated `#{attr}_changed?`. See #325
I didn't realize that this was breaking backward compat' because we check your ActiveRecord version. So if you upgrade, existing methods named `#{attr}_changed?` won't be called.
I refactored it to the "first responding method", both will be tested, regardless of your Rails version. I added more tests for this.
I added this in the same PR but it could be removed to merge the fix independantly. I added a method called `algolia_dirty?`, you can define it to …
> Fix _changed? BC break and introduce algolia_dirty? method

- lib/algoliasearch-rails.rb
| Related Issue     | Fix #340
If indexing is disabled, do not get all of the changed attributes
In testing, we often have stubs that will break when trying to index. As a result we by
default set `disable_indexing: proc { Rails.env.test? }`. This is breaking after upgrading
algolia
> Do not check attributes for disabled indexes

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
| Related Issue     | Fix #352 #353
Fix breaking change introduced in #352
According to the [documentation](https://github.com/algolia/algoliasearch-rails/blob/master/README.md#custom-attribute-definition),
using custom attributes without a custom `_changed?` method will always
cause changes to push to the API. This behavior was lost in #338
Fix unexpected behavior during transactions #353
`@algolia_must_reindex` is reset in every validate call. This means that a record
that is updated multiple times in a transaction will only be indexed if the
final update marks as must reindex. Update the code so that once …
> Fix #352 and #353 

- lib/algoliasearch-rails.rb
- lib/algoliasearch/tasks/algoliasearch.rake
- lib/algoliasearch/utilities.rb
The Rails integration will compare your local settings and the index settings in Algolia when using an index. It can leads to a lot of getSettings calls so I introduce a new `check_settings` option that can disable this behavior if set to false.
Example
```ruby
class Musician < ActiveRecord::Base
include AlgoliaSearch
algoliasearch per_environment: true, check_settings: false do
searchableAttributes ['name', 'band']
end
end
```
If you use this feature, you will need to push settings manually when you modify them in your model configuration. This PR also add a new `rake algoliasearch:set_all_settings` command to push settings for all models.
It inherit settings from primary indices and set settings to replicas and additional indices.
> Disable settings change checks and introduce set_all_settings command

- Gemfile
- lib/algoliasearch/configuration.rb
**Please not that this PR shouldn't be released before the ruby client v1.23.0 is out** because we need this PR: https://github.com/algolia/algoliasearch-client-ruby/pull/282
Please see https://gist.github.com/julienbourdeau/7c11df8647e85f5fc7eac9d2c017e52c
> Pass Rails framework version for UserAgent

- ChangeLog
- Gemfile
- algoliasearch-rails.gemspec
- lib/algoliasearch-rails.rb
- lib/algoliasearch/version.rb
Use temporary index to preserve synonyms, settings, and rules.
Upgrade to latest ruby API clients.
> Use temporary index to preserve synonmys, settings, and rules

- .travis.yml
| Related Issue     | no
Set dist to trusty in .travis.yml
Failing builds for Ruby 1.8.7.
> A try to fix builds. Set dist to trusty for Ruby 1.8.7

- README.md
> docs(README): update link to doc

- lib/algoliasearch-rails.rb
| Related Issue     | -
This code append indexLanguages option management ability.
Currently, we cannot manage indexLanguages option via Rails codes.
> add indexLanguages option handler

- .travis.yml
- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
| Related Issue     | Fix #376
- Ruby 2.7 compatibility (warning fix)
- Rename test naming using convention `it should` prefix
Fix `/usr/local/bundle/ruby/2.7.0/gems/algoliasearch-rails-1.23.2/lib/algoliasearch-rails.rb:392: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead` warning on ruby 2.7
> Fix ruby warning 'Proc.new is deprecated'

- lib/algoliasearch/utilities.rb
In Rails 6, model loading is no longer working. This is because Zeitwerk has
replaced the original code loading. We now use Zeitwerk if it's available.
| Related Issue     | n/a  
Fix model loading in Rails 6 when using Zeitwork
Model loading doesn't work in Rails 6
> Use Zeitwerk for loading models in Rails 6

- Gemfile
- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
Previously, only a latitude & longitude couple could be passed to geoloc
Now, a larger set in the array form of:
`[{ lat: x_1, lng: y_1 }, ..., { lat: x_n, lng: y_n }]` can be passed,
through a block as below:
```
geoloc do
geoloc_array
end
```
| Related Issue     | Fix #370
Still accept simple latitude & longitude passing, but also an array of several hashes containing different coordinates.
Array passing of multiple latitudes & longitudes.
> Introduce: pass array argument to geoloc

- lib/algoliasearch/pagination/kaminari.rb
| New feature?      |no    
| Need Doc update   |no
Ruby 3.0 will not splat arguments on default
wrong number of arguments (given 2, expected 0..1)
> fix ruby 3.0 default splat behavior

- README.md
- lib/algoliasearch/configuration.rb
- spec/integration_spec.rb
- spec/utilities_spec.rb
| New feature?      |no
| BC breaks?        | no 
| Related Issue     | None
force the setting of `symbolize_keys: false` as this project breaks without this setting
undefined method .map for nil in https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch-rails.rb#L690
> Algolia v2 symbolizes keys

- lib/algoliasearch-rails.rb
| Related Issue     | no
Added condition to check if `check_settings` is `true` before retrieving index settings.
An extra call to get index settings performs even if `check_settings` is `false` as it described here https://www.algolia.com/doc/framework-integration/rails/index-configuration/index-settings/?language=ruby#synchronizing-settings
> Prevent an extra get_settings call even if check_settings is false

- lib/algoliasearch/configuration.rb
| New feature?      | yes
| Related Issue     | Fix #417 
This allows users to set `client_opts` on the configuration class, which will be forwarded to the Algolia client set up. This allows users to e.g. pass a custom logger to prevent the Algolia API client from using the default one, which writes to `debug.log`.
> feat: allow to set client options

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
| Related Issue     | Fix #412 
This prevents a call to `get_settings` when indexing is disabled.
> fix: only check current settings when indexing enabled

- lib/algoliasearch-rails.rb
| New feature?      | no 
| Related Issue     | none
After upgrading from Ruby 2.6.8 to 2.7.4, Algolia was throwing all kinds of errors when trying to index records.
The error was `FrozenError: can't modify frozen String: "User"`, and it was related to [this line](https://github.com/algolia/algoliasearch-rails/pull/418/files#diff-306cbaf0638b0091914db232c4cb2c9eeb376b19119786da3d1648b5c6185f3dL214) around `force_encoding` which was triggered because we had `force_utf8_encoding: true` in our [algolia_options](https://github.com/algolia/algoliasearch-rails#utf-8-encoding) on all models.
> Fix issue with FrozenError around force_encoding

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
| Related Issue     | -
If you set customRanking as an empty Array, like below, Algolia understands that you set the customRanking as *null*.
```ruby
class Product < ActiveRecord::Base
include AlgoliaSearch
algoliasearch do
customRanking [] # emptry Array
end
end
```
As a result, the index setting API ( `/1/indexes/%s/settings?getVersion=1` ) returns setting information like below.
customRanking is nil.
```ruby
=> {
"minWordSizefor1Typo"=>4,
"minWordSizefor2Typos"=>8,
"hitsPerPage"=>20,
"maxValuesPerFacet"=>100,
"version"=>1,
"customRanking"=>nil # API's response, raw JSON, is "customRanking":null
}
```
This behavior is …
> fix:settings changes detection issue with empty array

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
| Related Issue     | -
If you use `inherit` option for replica following [this document](https://github.com/algolia/algoliasearch-rails#primaryreplica), the settings changes check function ( `algoliasearch_settings_changed?` ) falsely detects the changes.
This function always detects that there is a change, even if there is no change.
The reason is simple.
The setting Hash building process, that should be done before the diff check process, is handled after the checking currently.
Therefore, when comparing replica index settings that use the `inherit` option, the comparison process is being performed with the `replicas` …
> fix: settings changes detection issue for replica indexes with inherit opt

- lib/algoliasearch-rails.rb
| Related issue | -
| Need Doc update   |  no
Add relevancyStrictness to IndexSettings which is used when configuring virtual replicas.
Currently we cannot manage this attribute with the gem
> Add relevancyStrictness to IndexSettings

- lib/algoliasearch-rails.rb
This resolves a conflict of using this gem with `rodauth-rails` and using ActiveRecord.
Adds checks for `Sequel::Model` being defined.
While using this gem and `rodauth-rails` at the same time you get an 
```ruby
NameError (uninitialized constant Sequel::Model):
```
error because `rodauth-rails` loads `Sequel` but not `Sequel::Model`
> Check both Sequel and Sequel::Model are defined.

- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
This PR changes how we detect changes to the record in case a custom objectID is used. If a method is used to define the objectID, we currently always assumed it has changed, while we should assume it hasn't changed by default.
> fix: don't consider objectID changed if using custom attribute

- CHANGELOG.MD
- lib/algoliasearch/configuration.rb
| Bug fix?          | yes (ish)
| New feature?      | yes (ish)
| BC breaks?        | yes (ish?)    
Currently the default options are merged into the user-supplied configuration which means that any user supplied configuration for the user agent would be overwritten.
This could technically be described as a breaking change, but only if the user was relying on a somewhat odd behaviour. They'd have to set a configuration value then rely on it being overwritten. I can't think of a use case for that, but if someone was doing something interesting with a proxy that sniffs user-agent, and had done the above they might technically have a breakage. Otherwise, I'd usually describe this as a bugfix.
This means users …
> Allow configuring user agent / other default options

- lib/algoliasearch/algolia_job.rb
- lib/algoliasearch/configuration.rb
- spec/integration_spec.rb
- spec/spec_helper.rb
| New feature?      | yes
| BC breaks?        | no, provided #438 merged first / removed  
| Related Issue     | Makes progress towards https://github.com/algolia/algoliasearch-rails/issues/85
Copy-pasted from commit message:
```
Allow library users to specify default ActiveJob queue for indexing
The current auto_indexing behaviours are great, but force a user to
effectively reimplement the default enqueue behaviour if they just wanna
use a different ActiveJob queue. Instead, allow the queue_name to
specified as a configuraiton option, but fallback to the default if no
value is set.
Someone who just updates to a version with this commit should see no
difference until they supply a …
```
> Allow configuration ActiveJob queue for auto_index

- Gemfile
- algoliasearch-rails.gemspec
- lib/algoliasearch-rails.rb
- lib/algoliasearch/pagination.rb
- lib/algoliasearch/pagination/pagy.rb
- spec/integration_spec.rb
| New feature?      | yes    
| Related Issue     |  https://github.com/algolia/algoliasearch-rails/issues/444 
This change adds support for [pagy](https://github.com/ddnexus/pagy) as a pagination backend.
Co-authored by: [Ryan Wolfe](https://github.com/RyanJWolfe/RyanJWolfe)
Currently when using algolia with pagy, we have to use pagy_array which means that we are pulling the entire result set for every page. This is not optimal.
Even if we **highly recommend to perform all search (and therefore pagination) operations from your frontend using JavaScript**, 
we support the following as pagination backends: …
> Add support for Pagy as pagination backend

- .circleci/config.yml
- .github/workflows/issue.yml
- CHANGELOG.MD
- Gemfile
- UPGRADING_TO_V3.MD
- algoliasearch-rails.gemspec
- lib/algoliasearch-rails.rb
- lib/algoliasearch/configuration.rb
- lib/algoliasearch/pagination/pagy.rb
- lib/algoliasearch/version.rb
- spec/integration_spec.rb
- spec/spec_helper.rb
| New feature?      | yes
| BC breaks?        | yes-ish  
| Related Issue     | Fix #447 
This upgrades the RoR client to support v3 of the Algolia API client. This introduces some breaking changes, mostly in responses when doing a search and some methods that are deprecated or change return types. I'll try to document these breaking changes as best as I can.
> feat: upgrade to newest API client version

- lib/algoliasearch-rails.rb
| BC breaks?        | no 
| Related Issue     | 
`app/models/product.rb`
```
class Product < ApplicationRecord
enum status: {
draft: 0,
opened: 1,
}
algoliasearch if: :algolia_published? do
attribute :title
attribute :content
end
def algolia_published?
opened?
end
end
```
in rails console for instance
```
Product.draft.limit(3).reindex!
```
Got the error below
```
NoMethodError: undefined method `task_id' for nil:NilClass
/Users/metheglin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/algoliasearch-rails-3.0.0/lib/algoliasearch-rails.rb:464:in `block (2 levels) in algolia_reindex!'
/Users/metheglin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-7 …
```
> Bugfix reindex! when all of targeted records are to delete and nothing to save

- lib/algoliasearch-rails.rb
| Bug fix?          | Probably yes
| New feature?      | Probably no
| BC breaks?        | Probably no     
| Related Issue     | 
| Need Doc update   | Probably no
Atomic reindex (ex: `Product.reindex`) is always going to create tmp index with empty setting. And index move completed, previous settings disappeared. Not only specified settings inside algoliasearch block, but manual setting on dashboard.
`app/models/product.rb`
```
class Product < ApplicationRecord
algoliasearch check_settings: true do
attribute :title
attribute :content
attribute :updated_at_i
customRanking ['desc(updated_at_i)']
searchableAttributes ['title']
indexLanguages ['ja']
end
end
```
in rails console for instance
```
Product.reindex
```
I understood the …
> Fixed atomic reindex to ensure init when check_settings=true.

- Gemfile
- lib/algoliasearch-rails.rb
- spec/integration_spec.rb
| Need Doc update |  no
Re introduce variable check to avoid unecessary re initialization of already set indices.
in [v2 we used to have](https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch-rails.rb#L774):
```ruby
return @algolia_indexes[settings] if @algolia_indexes[settings]
@algolia_indexes[settings] = SafeIndex.new(algolia_index_name(options), algoliasearch_options[:raise_on_failure])
index_settings ||= settings.to_settings
```
basically keeping track of indices that were already initialized in `@algolia_indexes`. For some reason [v3 is doing](https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch-rails.rb#L767#L774):
```ruby …
```
> bugfix: avoid re initializing index
